---
title: "Correlogram"
author: "Asta Kvedaraitė"
date: "6/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
beta <- readRDS("../../Komanda/output/betab.rds")
anno <- readRDS("../../Komanda/output/annotation.rds")
sample <- read.csv("../output/sampleKey.csv",  as.is = TRUE)


```

```{r}
#packages

#if(!require("corrgram"))install.packages("corrgram")
library("corrgram")
library(GGally)

```

```{r}

region1 <- sample[sample$tissue_region == "DLPFC",][1:2,]
region2 <- sample[sample$tissue_region == "CRB",][1:2,]
region3 <- sample[sample$tissue_region == "ERC",][1:2,]
region4 <- sample[sample$tissue_region == "HIPPO",][1:2,]

reg <- rbind(region1, region2, region3, region4)

vars <- rowVars(beta)
#vars
#vars <- data.frame(vars = vars, ind = c(1:length(vars)))
#vars
vars <- order(vars, decreasing = TRUE)
#positions in beta
vars <- vars[1:10000]

data <- beta[vars,reg$sample_id]
#data <- beta[,]
data <- as.data.frame(data)

dim(data)


```

```{r}

corrgram(data, order=FALSE, lower.panel=panel.shade,
  upper.panel=panel.pie, text.panel=panel.txt,
  main="Samples from each brain region")

```

```{r}
colnames(data)[3]

rbind(sample[sample$sample_id == colnames(data)[3],],
    sample[sample$sample_id == colnames(data)[4],],
    sample[sample$sample_id == colnames(data)[5],])

#sample[sample$geo_accession == "GSM3584326",]
```


```{r}
ggpairs(data[1:1000,]) 

sample
```
