---
title: "Graphs"
author: "Asta Kvedaraitė"
date: "5/14/2020"
output:
  word_document: default
  html_document: default
---
```{r echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  error = TRUE,
  echo = FALSE 
)
```

```{r}
#if(!require("treemap"))install.packages("treemap")
#if(!require("d3treeR"))install.packages("d3treeR")
#if(!require("hrbrthemes"))install.packages("hrbrthemes")
```
# Dendrogram 
```{r}
sample <- read.csv("../../2darbas/output/correctedSample.csv")
beta <- readRDS("../../2darbas/output/betab.rds")
anno <- readRDS("../../Komanda/output/annotation.rds")

#head(sample)
#head(as.data.frame(anno))
#head(as.data.frame(beta))

library("S4Vectors")
#head(sample)
#head(as.data.frame(anno))
#head(as.data.frame(beta))
print ("unique sample plates :")
unique(sample$sample_plate)
chr8 <- anno[anno$chr == "chr8",]
chr8body <- chr8[chr8$UCSC_RefGene_Group == "Body",]
print(paste0("nrow chr8 : ",nrow(chr8body)))
#as.data.frame(chr8body)
chr8bodyI <- chr8body[chr8body$Type == "I",]
#as.data.frame(chr8bodyI)
print(paste0("chr8, group - body and type I : row count :",nrow(chr8bodyI)))
plate1 <- sample[sample$sample_plate == " Plate 1",]
#plate1
print(paste0("nrow plate_1 : ", nrow(plate1)))
data <- beta[chr8bodyI$Name, plate1$sample_id]
print(paste0("data row count : ", nrow(data)))
print(paste0("data column count : ", ncol(data)))
#as.data.frame(data)
```

```{r}

tm <- matrix(nrow = nrow(data), ncol = 2)
#tm[1:5, 1:2]
for (i in 1:nrow(data)){
    mean <- mean(as.numeric(data[i,]))
    tm[i,] <- c(rownames(data)[i], mean)
}
tm <- tm[order(tm[,2], decreasing = TRUE),]

tdata <- t(data[tm[1:100,1],])
tdata <- as.data.frame(tdata)
tdata$status <- plate1$sample
#tdata

hc <- hclust(dist(tdata))
dhc <- as.dendrogram(hc)
plot(hc, labels = FALSE)

# set the margin
par(mar=c(4,4,2,2))

# Plot the Second group
plot(dhc[[1]], main= "zoom on the left")
plot(dhc[[1]][[2]], main= "zoom on the right")
plot(dhc[[1]][[2]][[2]],  main= "zoom on the right")
plot(dhc[[1]][[2]][[2]][[2]] , main= "zoom on the right")
par(mfrow = c(1, 1))
```


```{r}
#So if I Want to color each leaf of the Tree, I have to change the attribute of each leaf. This can be done using the dendrapply function. So I create a function that # # add 3 attributes to the leaf : one for the color (“lab.col”) ,one for the font “lab.font” and one for the size (“lab.cex”).
i=0
last <- ncol(tdata)
colLab<<-function(n){
    if(is.leaf(n)){
        
        #I take the current attributes
        a=attributes(n)
        
        #I deduce the line in the original data, and so the treatment and the specie.
        #print(as.character(rownames(tdata)));
        #print(paste0("a : " , a$label, " ", i));
        ligne <- match(attributes(n)$label,rownames(tdata))
        #print(paste0("tdata : ", tdata[ligne,last]))
        #print(paste0("ligne : ", ligne));
        #print(as.character(tdata[ligne,last]))
        control <- as.character(tdata[ligne,last]);
        #print(control)
        #print(paste0("control : ", control));
        if(control=="Control"){col_con="blue"};
        if(control=="Alzheimer"){col_con="red"};
        
        #Modification of leaf attribute
        attr(n,"nodePar")<-c(a$nodePar,list(cex=1.5,lab.cex=1,pch=20,col=col_con, 
                                            lab.col = col_con,lab.font=1,lab.cex=1))
        }
    return(n)
}
# Finally I just have to apply this to my dendrogram
dL <- dendrapply(dhc, colLab)
plot(dL , main="Chromosome 8 , Plate_1 and type I")
legend("top", title = "Sample status",
     legend = c("Alzheimer", "Control"), 
     col = c("red", "blue"), 
     pch = c(20,20), bty = "n",  pt.cex = 1.5, cex = 0.8 , 
     text.col = "black", horiz = FALSE, inset = c(0, 0.1))
```
