---
title: "Parallel coordinates"
author: "Asta Kvedaraitė"
date: "5/14/2020"
output:
  word_document: default
  html_document: default
---
```{r echo = FALSE, message=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  error = FALSE,
  echo = FALSE 
)
```

```{r}
#if(!require("treemap"))install.packages("treemap")
#if(!require("d3treeR"))install.packages("d3treeR")
#if(!require("hrbrthemes"))install.packages("hrbrthemes")
```
# Dendrogram 
```{r}
sample <- read.csv("../../2darbas/output/correctedSample.csv")
beta <- readRDS("../../2darbas/output/betab.rds")
anno <- readRDS("../../Komanda/output/annotation.rds")
library("S4Vectors")
#head(sample)
#head(as.data.frame(anno))
#head(as.data.frame(beta))
print ("unique sample plates :")
unique(sample$sample_plate)
chr8 <- anno[anno$chr == "chr8",]
chr8body <- chr8[chr8$UCSC_RefGene_Group == "Body",]
print(paste0("nrow chr8 : ",nrow(chr8body)))
#as.data.frame(chr8body)
chr8bodyI <- chr8body[chr8body$Type == "I",]
#as.data.frame(chr8bodyI)
print(paste0("chr8, group - body and type I : row count :",nrow(chr8bodyI)))
plate1 <- sample[sample$sample_plate == " Plate 1",]
#plate1
print(paste0("nrow plate_1 : ", nrow(plate1)))
data <- beta[chr8bodyI$Name, plate1$sample_id]
print(paste0("data row count : ", nrow(data)))
print(paste0("data column count : ", ncol(data)))
#as.data.frame(data)
```

```{r}

hc <- hclust(dist(data))
dhc <- as.dendrogram(hc)

# set the margin
par(mar=c(4,4,2,2))

# Plot the Second group
plot(dhc[[2]] , main= "zoom on a part of the dendrogram")
specific_leaf <- dhc[[2]][[1]][[2]]
plot(specific_leaf)

plot(hc, labels = FALSE)

```
```{r}
if(!require("GGally"))install.packages("GGally")
library(GGally)
library(ggplot2)
library(hrbrthemes)
library(moduleColor)


tm <- matrix(nrow = nrow(data), ncol = 2)
#tm[1:5, 1:2]
for (i in 1:nrow(data)){
    mean <- mean(as.numeric(data[i,]))
    tm[i,] <- c(rownames(data)[i], mean)
}
tm <- tm[order(tm[,2], decreasing = TRUE),]

tdata <- t(data[tm[1:100,1],])
tdata <- as.data.frame(tdata)
tdata$status <- plate1$sample
#tdata
#for (i in 1:ncol(tdata)){
#  if (as.character(tdata$status[i]) == "Control") {
#    tdata$stnum[i] <- 2 
#  }else {
#    tdata$stnum[i] <- 4 
#  }
#}

#typeof(plate1$sample)
#as.character(plate1$sample)
ggparcoord(tdata,
    columns = 1:(ncol(tdata)-1), groupColumn = ncol(tdata),
    scale="uniminmax",
     showPoints = TRUE
    )
```



